# Generated by Django 5.0.1 on 2024-08-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
