# Generated by Django 5.0.1 on 2024-08-16 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0002_alter_eventmodel_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='Subcity',
        ),
    ]
